{"name": "Переход по меню на другие страницы", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: Expected redirection to \"https://www.way2automation.com/python/training/appium-python-training/\", but got \"https://www.way2automation.com/\"", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9fac6c571191bb825983aea903e97bb9\")>\n\n    @allure.severity(severity_level.MINOR)\n    @allure.epic(\"Smoke тест\")\n    @allure.feature(\"Скриншот упавшего теста\")\n    @allure.testcase(\"Задачи U1, U2, U4\")\n    @allure.story(\"При падении теста делается скриншот\")\n    @allure.title(\"Переход по меню на другие страницы\")\n    @allure.description(\n        \"\"\"\n        Цель: Проверка перехода по меню на другие страницы\n    \n        Предусловие:\n            - Открыть браузер\n    \n        Шаги:\n            1. Открыть домашнюю страницу\n            2. Навести курсор на вкладку меню \"All Courses\"\n            3. Проверить переход на страницу\n            4. Проверить значение \"TITLE\"\n            5. Проверить корректность отображения элементов страницы\n    \n        Ожидаемый результат:\n            - Происходит переход на страницу\n            - Значение \"TITLE\" соответствует странице\n            - Элементы, уникальные для этой страницы, активны\"\"\")\n    @pytest.mark.xfail\n    def test_redirect_to_appium_python(browser: fixture):\n        menu = Menu(browser)\n        menu.open_homepage()\n        menu.hover_over_all_courses()\n>       menu.assert_redirection_to_appium_python()\n\ntests/test_failure_screenshot.py:102: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.home_page.Menu object at 0x7f25977a0470>\n\n    def assert_redirection_to_appium_python(self) -> None:\n        with allure.step('Проверить переход на страницу'):\n            curr_url = self.get_current_url()\n            expected_url = MenuUrls.appium_python\n>           assert curr_url == expected_url, f'Expected redirection to \"{expected_url}\", but got \"{curr_url}\"'\nE           AssertionError: Expected redirection to \"https://www.way2automation.com/python/training/appium-python-training/\", but got \"https://www.way2automation.com/\"\n\npages/home_page.py:73: AssertionError"}, "description": "\n    Цель: Проверка перехода по меню на другие страницы\n\n    Предусловие:\n        - Открыть браузер\n\n    Шаги:\n        1. Открыть домашнюю страницу\n        2. Навести курсор на вкладку меню \"All Courses\"\n        3. Проверить переход на страницу\n        4. Проверить значение \"TITLE\"\n        5. Проверить корректность отображения элементов страницы\n\n    Ожидаемый результат:\n        - Происходит переход на страницу\n        - Значение \"TITLE\" соответствует странице\n        - Элементы, уникальные для этой страницы, активны", "steps": [{"name": "Открыть домашнюю страницу", "status": "passed", "start": 1735767229450, "stop": 1735767230868}, {"name": "Навести курсор на вкладку меню \"All Courses\"", "status": "passed", "start": 1735767230868, "stop": 1735767231158}, {"name": "Проверить переход на страницу", "status": "failed", "statusDetails": {"message": "AssertionError: Expected redirection to \"https://www.way2automation.com/python/training/appium-python-training/\", but got \"https://www.way2automation.com/\"\n", "trace": "  File \"/home/runner/work/internship_u/internship_u/pages/home_page.py\", line 73, in assert_redirection_to_appium_python\n    assert curr_url == expected_url, f'Expected redirection to \"{expected_url}\", but got \"{curr_url}\"'\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1735767231159, "stop": 1735767231352}, {"name": "Скриншот упавшего теста", "status": "passed", "attachments": [{"name": "Test failure screenshot", "source": "2520c553-cff7-4085-9e1f-1a209ee9282b-attachment.png", "type": "image/png"}], "start": 1735767231353, "stop": 1735767231720}], "start": 1735767229450, "stop": 1735767231353, "uuid": "8d388409-6271-4f2d-b673-51627a3e104d", "historyId": "050c982e024853c3c5cd5085195683a1", "testCaseId": "050c982e024853c3c5cd5085195683a1", "fullName": "tests.test_failure_screenshot#test_redirect_to_appium_python", "labels": [{"name": "story", "value": "При падении теста делается скриншот"}, {"name": "feature", "value": "Скриншот упавшего теста"}, {"name": "severity", "value": "minor"}, {"name": "epic", "value": "Smoke тест"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_failure_screenshot"}, {"name": "host", "value": "fv-az1333-799"}, {"name": "thread", "value": "2587-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_failure_screenshot"}], "links": [{"type": "tms", "url": "Задачи U1, U2, U4", "name": "Задачи U1, U2, U4"}]}